/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author pc
 */
public class PanelEtudiant extends javax.swing.JPanel {
    
    dao.EtudiantDaoImpl dao = new dao.EtudiantDaoImpl();
    
   javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
  

    /**
     * Creates new form PanelEtudiant
     */
    public PanelEtudiant() {
        initComponents();
        chargerTableau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFiliere = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNiveau = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEtudiants = new javax.swing.JTable();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        txtRecherche = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nom :");

        jLabel2.setText("Filière :");

        txtFiliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiliereActionPerformed(evt);
            }
        });

        jLabel3.setText("Niveau :");

        txtNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNiveauActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        tableEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEtudiants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEtudiantsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableEtudiants);

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        txtRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheActionPerformed(evt);
            }
        });
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(txtFiliere)
                            .addComponent(txtNiveau)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModifier)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupprimer)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiliereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiliereActionPerformed

    private void txtNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNiveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNiveauActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
   int ligneSelectionnee = tableEtudiants.getSelectedRow();
    if (ligneSelectionnee == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sélectionnez un étudiant à modifier !");
        return;
    }

    int id = Integer.parseInt(tableEtudiants.getValueAt(ligneSelectionnee, 0).toString());
    
    String nom = txtNom.getText();
    String filiere = txtFiliere.getText();
    String niveau = txtNiveau.getText();
    
   entites.Etudiant e = new entites.Etudiant(nom, filiere, niveau);
    e.setId(id); // Important : on garde le même ID !

    if (dao.update(e)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Modification réussie !");
        chargerTableau();
        txtNom.setText("");
        txtFiliere.setText("");
        txtNiveau.setText("");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de la modification.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed

if (txtNom.getText().trim().isEmpty() || txtFiliere.getText().trim().isEmpty()) {
    
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Veuillez remplir tous les champs (Nom et Filière) !", 
        "Champs manquants", 
        javax.swing.JOptionPane.WARNING_MESSAGE);
    
   return; 
}
  String nom = txtNom.getText();
        String filiere = txtFiliere.getText();
        String niveau = txtNiveau.getText();
   
        entites.Etudiant e = new entites.Etudiant(nom, filiere, niveau);
        
       if(dao.create(e)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Étudiant ajouté avec succès !");
            
          chargerTableau();
            txtNom.setText("");
            txtFiliere.setText("");
            txtNiveau.setText("");
            txtNom.requestFocus();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout.");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed

    int ligneSelectionnee = tableEtudiants.getSelectedRow();
    
    if (ligneSelectionnee == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Veuillez sélectionner un étudiant !");
        return;
    }
    
    int choix = javax.swing.JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer cet étudiant ?", "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (choix == javax.swing.JOptionPane.YES_OPTION) {
      int id = Integer.parseInt(tableEtudiants.getValueAt(ligneSelectionnee, 0).toString());
        
       if (dao.delete(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Suppression réussie !");
            chargerTableau();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de la suppression.");
        }
    }      
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void tableEtudiantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEtudiantsMouseClicked
int ligne = tableEtudiants.getSelectedRow();
    
    txtNom.setText(tableEtudiants.getValueAt(ligne, 1).toString());
    txtFiliere.setText(tableEtudiants.getValueAt(ligne, 2).toString());
    txtNiveau.setText(tableEtudiants.getValueAt(ligne, 3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tableEtudiantsMouseClicked

    private void txtRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheActionPerformed
     
    }//GEN-LAST:event_txtRechercheActionPerformed

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
     try {
        String motCle = txtRecherche.getText();
        
       javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableEtudiants.getModel();
        model.setRowCount(0);
        
        java.sql.Connection conn = connexion.Connexion.getConnection();
        
        String req = "SELECT * FROM etudiant WHERE nom LIKE ?";
        java.sql.PreparedStatement ps = conn.prepareStatement(req);
        
       ps.setString(1, "%" + motCle + "%");
        
        java.sql.ResultSet rs = ps.executeQuery();
                
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"), 
                rs.getString("nom"), 
                rs.getString("filiere") 
            });
        }
    } catch (Exception e) {
        System.out.println("Erreur de recherche : " + e.getMessage());
    }
    }//GEN-LAST:event_txtRechercheKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableEtudiants;
    private javax.swing.JTextField txtFiliere;
    private javax.swing.JTextField txtNiveau;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables

   private void chargerTableau() {
       model.setColumnIdentifiers(new String[]{"ID", "Nom", "Filière", "Niveau"});
        tableEtudiants.setModel(model);
        
       model.setRowCount(0);
        
       for (entites.Etudiant e : dao.findAll()) {
            model.addRow(new Object[]{ e.getId(), e.getNom(), e.getFiliere(), e.getNiveau() });
        }
    }
}
