/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author pc
 */
public class PanelModule extends javax.swing.JPanel {

    /**
     * Creates new form PanelModule
     */
    public PanelModule() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNom = new javax.swing.JLabel();
        txtCoefficient = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableModules = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtNom.setText("Nom du module :");

        txtCoefficient.setText("Coefficient :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableModules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableModules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableModulesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableModules);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNom)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtCoefficient)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoefficient))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
       String nom = jTextField1.getText();

       int coefficient = Integer.parseInt(jTextField2.getText());

      
        entites.Module nouveauModule = new entites.Module(nom, coefficient);

        dao.ModuleDaoImpl moduleDao = new dao.ModuleDaoImpl();
        
        if (moduleDao.create(nouveauModule)) {
           
            javax.swing.JOptionPane.showMessageDialog(this, "Module ajouté avec succès !");
            
           
            txtNom.setText("");
            txtCoefficient.setText("");
            
           refreshTable();
            
       } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout en base de données.");
        }
        
    } catch (NumberFormatException e) {
      javax.swing.JOptionPane.showMessageDialog(this, "Attention : Le coefficient doit être un nombre !");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                        
        try {
           int ligneSelectionnee = tableModules.getSelectedRow();
            
            if (ligneSelectionnee == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Veuillez d'abord sélectionner un module dans le tableau !");
                return; 
            }
            
           int idModule = Integer.parseInt(tableModules.getValueAt(ligneSelectionnee, 0).toString());
            
            int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ce module ?", "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
            
            if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
                dao.ModuleDaoImpl dao = new dao.ModuleDaoImpl();
               dao.delete(idModule);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Module supprimé avec succès !");
                
              refreshTable();
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de la suppression : " + e.getMessage(), "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        }                                        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
        try {
          int ligneSelectionnee = tableModules.getSelectedRow();
            
            if (ligneSelectionnee == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Veuillez sélectionner un module dans le tableau pour le modifier !");
                return;
            }
            
            int idModule = Integer.parseInt(tableModules.getValueAt(ligneSelectionnee, 0).toString());
            
            String nouveauNom = jTextField1.getText();
            int nouveauCoef = Integer.parseInt(jTextField2.getText());
            
            entites.Module moduleModifie = new entites.Module();
            moduleModifie.setId(idModule); 
            moduleModifie.setNom(nouveauNom);
            moduleModifie.setCoefficient(nouveauCoef);
            
            dao.ModuleDaoImpl dao = new dao.ModuleDaoImpl();
            dao.update(moduleModifie);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Module modifié avec succès !");
            
            jTextField1.setText("");
            jTextField2.setText("");
            
           refreshTable();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le coefficient doit être un nombre !", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de la modification : " + e.getMessage(), "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        }                                        
          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableModulesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableModulesMouseClicked
    try {
       int ligne = tableModules.getSelectedRow();
        
      String nomModule = tableModules.getValueAt(ligne, 1).toString();
        String coefficient = tableModules.getValueAt(ligne, 2).toString();
        
       jTextField1.setText(nomModule);
        jTextField2.setText(coefficient);
        
    } catch (Exception e) {
        System.out.println("Erreur lors du clic sur le tableau : " + e.getMessage());
    } 
    }//GEN-LAST:event_tableModulesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tableModules;
    private javax.swing.JLabel txtCoefficient;
    private javax.swing.JLabel txtNom;
    // End of variables declaration//GEN-END:variables

private void refreshTable() {
    try {
        dao.ModuleDaoImpl dao = new dao.ModuleDaoImpl();
        java.util.List<entites.Module> liste = dao.findAll();

        String[] colonnes = {"ID", "Nom du Module", "Coefficient"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(colonnes, 0);

       for (entites.Module m : liste) {
            Object[] ligne = {m.getId(), m.getNom(), m.getCoefficient()};
            model.addRow(ligne);
        }

       tableModules.setModel(model);

    } catch (Exception e) {
        System.out.println("Erreur chargement tableau : " + e.getMessage());
    }
}

}
