package presentation;

import dao.EtudiantDaoImpl;

/**
 *
 * @author pc
 */
public final class PanelAccueil extends javax.swing.JPanel {
    private Object mDao;
    private Object Dao;

  
    public PanelAccueil() {
        initComponents();
        mettreAJourStats();
        afficherGraphique();
    }
public void mettreAJourStats() {
    
    
        try {
       
            org.jfree.data.general.DefaultPieDataset dataset = new org.jfree.data.general.DefaultPieDataset();
            
         
            java.sql.Connection conn = connexion.Connexion.getConnection(); 
            java.sql.Statement st = conn.createStatement();
            
        
            String req = "SELECT filiere, COUNT(*) as nombre FROM etudiant GROUP BY filiere";
            java.sql.ResultSet rs = st.executeQuery(req);
            
         
            while (rs.next()) {
                String nomFiliere = rs.getString("filiere");
                int nombreEtudiants = rs.getInt("nombre");
                dataset.setValue(nomFiliere, nombreEtudiants);
            }
            
            // 4. Dessiner le "Camembert" (Pie Chart)
            org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createPieChart(
                "Répartition des Étudiants", // Le titre au-dessus du graphique
                dataset,                     // Les données
                true,                        // Afficher la légende en bas
                true,                        // Afficher les infos quand on passe la souris
                false
            );
            
            // 5. Mettre le dessin dans le panelGraphique que tu viens de créer
            org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);
            panelGraphique.removeAll();
            panelGraphique.add(chartPanel, java.awt.BorderLayout.CENTER);
            panelGraphique.validate();
            
        } catch (Exception e) {
            System.out.println("Erreur d'affichage du graphique : " + e.getMessage());
        }
    
    

    try {
        
        dao.EtudiantDaoImpl eDao = new dao.EtudiantDaoImpl();
        dao.ModuleDaoImpl mDao = new dao.ModuleDaoImpl();
        dao.NoteDaoImpl nDao = new dao.NoteDaoImpl();
      
        int totalE = eDao.compterEtudiants();
        int totalM = mDao.compterModules();
        double moyenne = nDao.calculerMoyenneGenerale();
        
        lblTotalEtudiants.setText("Nombre d'étudiants : " + totalE);
        lblTotalModules.setText("Nombre de modules : " + totalM);
        lblMoyenneGenerale.setText("Moyenne Générale : " + moyenne + " / 20");
        
        
            System.out.println("Stats mises à jour !");
        } catch (Exception e) {
            System.out.println("Erreur stats : " + e.getMessage());
        }
    // Exemple : si tu as une classe EtudiantDAO
    // int total = EtudiantDAO.compterTout();
    // lblTotalEtudiants.setText("Total Étudiants : " + total);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalEtudiants = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalModules = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblMoyenneGenerale = new javax.swing.JLabel();
        panelGraphique = new javax.swing.JPanel();

        lblTotalEtudiants.setText("\"Total Etudiants : 0\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTotalEtudiants)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(lblTotalEtudiants)
                .addGap(33, 33, 33))
        );

        lblTotalModules.setText("\"Total Modules : 0\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(lblTotalModules))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTotalModules)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lblMoyenneGenerale.setText("\"Moyenne Générale : 0.0\"");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(lblMoyenneGenerale)
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblMoyenneGenerale, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelGraphique.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(panelGraphique, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGraphique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMoyenneGenerale;
    private javax.swing.JLabel lblTotalEtudiants;
    private javax.swing.JLabel lblTotalModules;
    private javax.swing.JPanel panelGraphique;
    // End of variables declaration//GEN-END:variables

   
public void afficherGraphique() {
        try {
            org.jfree.data.general.DefaultPieDataset dataset = new org.jfree.data.general.DefaultPieDataset();
            
            java.sql.Connection conn = connexion.Connexion.getConnection(); 
            java.sql.Statement st = conn.createStatement();
            
            String req = "SELECT filiere, COUNT(*) as nombre FROM etudiant GROUP BY filiere";
            java.sql.ResultSet rs = st.executeQuery(req);
            
            while (rs.next()) {
                dataset.setValue(rs.getString("filiere"), rs.getInt("nombre"));
            }
            
            org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createPieChart(
                "Répartition des Étudiants", 
                dataset,                     
                true,                        
                true,                        
                false
            );
            
            org.jfree.chart.ChartPanel chartPanel = new org.jfree.chart.ChartPanel(chart);
            panelGraphique.removeAll();
            panelGraphique.add(chartPanel, java.awt.BorderLayout.CENTER);
            panelGraphique.validate();
            
        } catch (Exception e) {
            System.out.println("Erreur d'affichage du graphique : " + e.getMessage());
        }
    }
 
}