/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class PanelNote extends javax.swing.JPanel {
     dao.EtudiantDaoImpl daoEtudiant = new dao.EtudiantDaoImpl();
    dao.ModuleDaoImpl daoModule = new dao.ModuleDaoImpl();
    dao.NoteDaoImpl daoNote = new dao.NoteDaoImpl();
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
    
    public PanelNote() {
        initComponents();
        chargerComboBoxes(); 
        chargerTableau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboEtudiant = new javax.swing.JComboBox();
        comboModule = new javax.swing.JComboBox();
        txtSession = new javax.swing.JTextField();
        txtValeur = new javax.swing.JTextField();
        btnAjouter = new javax.swing.JButton();
        btnModifie = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotes = new javax.swing.JTable();
        btnImprimer = new javax.swing.JButton();

        jLabel1.setText("Étudiant :");

        jLabel2.setText("Module :");

        jLabel3.setText("Session :");

        jLabel4.setText("Note :");

        comboEtudiant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboModule.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifie.setText("Modifier");
        btnModifie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifieActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        tableNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNotesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableNotes);

        btnImprimer.setText("Imprimer la liste");
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboEtudiant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboModule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSession)
                            .addComponent(txtValeur)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnAjouter)
                        .addGap(53, 53, 53)
                        .addComponent(btnModifie)
                        .addGap(55, 55, 55)
                        .addComponent(btnSupprimer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnImprimer)
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifie)
                    .addComponent(btnSupprimer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnImprimer)
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
     int ligne = tableNotes.getSelectedRow();
    if (ligne == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sélectionnez une note dans le tableau !");
        return;
    }

    int id = (int) model.getValueAt(ligne, 0);
    int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, "Supprimer cette note ?", "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
        if (daoNote.delete(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Note supprimée !");
            chargerTableau();
        }
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
          
        try {
    double note = Double.parseDouble(txtValeur.getText());
    if (note < 0 || note > 20) {
        JOptionPane.showMessageDialog(this, "La note doit être comprise entre 0 et 20 !");
        return;
    }
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Veuillez saisir un nombre valide pour la note !");
    return;
}
        
        if (txtValeur.getText().trim().isEmpty() || txtSession.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Erreur : Tous les champs doivent être remplis !", "Champ vide", JOptionPane.WARNING_MESSAGE);
    return; 
}                               
        try {
        
            entites.Etudiant etudiant = (entites.Etudiant) comboEtudiant.getSelectedItem();
            entites.Module module = (entites.Module) comboModule.getSelectedItem();
            
           
            String session = txtSession.getText();
            String valeurTexte = txtValeur.getText();
            
         
            if (session.isEmpty() || valeurTexte.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Veuillez remplir la session et la note !");
                return;
            }
            
           
            double valeur = Double.parseDouble(valeurTexte);
            
            entites.Note n = new entites.Note(etudiant, module, session, valeur);
            
           if(daoNote.create(n)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Note ajoutée avec succès !");
                chargerTableau();
                
         
                txtSession.setText("");
                txtValeur.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de la note.");
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Attention : La note doit être un nombre valide (ex: 15.5) !");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void tableNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNotesMouseClicked
                                           
    int ligne = tableNotes.getSelectedRow();
    
  String nomEtudiant = model.getValueAt(ligne, 1).toString();
    String nomModule = model.getValueAt(ligne, 2).toString();
    
    // On cherche dans les combos l'objet qui correspond au nom
    for (int i = 0; i < comboEtudiant.getItemCount(); i++) {
        if (comboEtudiant.getItemAt(i).toString().equals(nomEtudiant)) {
            comboEtudiant.setSelectedIndex(i);
        }
    }
    
    for (int i = 0; i < comboModule.getItemCount(); i++) {
        if (comboModule.getItemAt(i).toString().equals(nomModule)) {
            comboModule.setSelectedIndex(i);
        }
    }

    txtSession.setText(model.getValueAt(ligne, 3).toString());
    txtValeur.setText(model.getValueAt(ligne, 4).toString());
    // TODO add your handling code here:
    }//GEN-LAST:event_tableNotesMouseClicked

    private void btnModifieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifieActionPerformed
                                          
    int ligne = tableNotes.getSelectedRow();
    if (ligne == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Sélectionnez d'abord une note dans le tableau !");
        return;
    }

    try {
      
        int id = (int) model.getValueAt(ligne, 0);
        
     
        entites.Etudiant etudiant = (entites.Etudiant) comboEtudiant.getSelectedItem();
        entites.Module module = (entites.Module) comboModule.getSelectedItem();
        String session = txtSession.getText();
        double valeur = Double.parseDouble(txtValeur.getText());

      entites.Note n = new entites.Note(id, etudiant, module, session, valeur);
  if (daoNote.update(n)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Note modifiée avec succès !");
            chargerTableau(); // Rafraîchir l'affichage
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erreur : Vérifiez la saisie de la note.");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifieActionPerformed

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
     try {
       java.text.MessageFormat header = new java.text.MessageFormat("Liste des Notes des Étudiants");
        java.text.MessageFormat footer = new java.text.MessageFormat("Page {0,number,integer}");
        
       boolean complete = tableNotes.print(javax.swing.JTable.PrintMode.FIT_WIDTH, header, footer);
        
        if (complete) {
            javax.swing.JOptionPane.showMessageDialog(this, "Impression terminée avec succès !");
        }
    } catch (java.awt.print.PrinterException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erreur d'impression : " + e.getMessage());
    }   // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnModifie;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox comboEtudiant;
    private javax.swing.JComboBox comboModule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableNotes;
    private javax.swing.JTextField txtSession;
    private javax.swing.JTextField txtValeur;
    // End of variables declaration//GEN-END:variables

  private void chargerComboBoxes() {
        comboEtudiant.removeAllItems(); // On vide la liste par défaut
        comboModule.removeAllItems();

       daoEtudiant.findAll().stream().forEach((e) -> {
            comboEtudiant.addItem(e);
         });

      daoModule.findAll().stream().forEach((m) -> {
            comboModule.addItem(m);
         });
    }

    private void chargerTableau() {
        model.setColumnIdentifiers(new String[]{"ID", "Étudiant", "Module", "Session", "Note"});
        tableNotes.setModel(model);
        model.setRowCount(0);

        daoNote.findAll().stream().forEach((n) -> {
         
            model.addRow(new Object[]{ n.getId(), n.getEtudiant().getNom(), n.getModule().getNom(), n.getSession(), n.getValeur() });
         });
    }
    private void viderChamps() {
        txtSession.setText("");
        txtValeur.setText("");
        comboEtudiant.setSelectedIndex(0);
        comboModule.setSelectedIndex(0);
    }
}
